# Generated by Django 5.1.2 on 2025-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_rename_incomingitems_incomingitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='full_name',
            new_name='company_name',
        ),
    ]
