# Generated by Django 5.1.2 on 2025-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_remove_size_item_size_description_size_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
