# Generated by Django 5.1.2 on 2025-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_alter_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='base_price',
            new_name='initial_price',
        ),
    ]
