# Generated by Django 5.1.2 on 2025-03-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_rename_base_price_item_initial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
