# Generated by Django 5.1.2 on 2025-03-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
