# Generated by Django 5.1.2 on 2025-04-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_remove_user_status_delete_status_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
